// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpiarkdmsxxuuluuetjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwaWFya2Rtc3h4dXVsdXVldGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDk2MjgsImV4cCI6MjA2NjMyNTYyOH0.vQ29qdCZB2CWMsU1tDdREhQbQih7qgWveO9wvVdKWGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);